name: 参与开源之夏专访专栏
description: 如果您想推荐或自荐以为嘉宾参与专访，请选择本条模板填写内容
title: "[推荐或自荐嘉宾-姓名（专栏）]: "

body:
  - type: markdown
    attributes:
      value: |
        ### 标题格式
        格式为 `推荐或自荐嘉宾 - [姓名] （专栏名称）`
        例如：`推荐嘉宾 - 张三（个人专访）` 
        
  - type: input
    id: channel
    attributes:
      label: 专栏
      description: ｜
        目前有专栏 `个人专访`、`项目经验分享`。
        专栏形式可选择文字、播客和视频
    validations:
      required: true
      
  - type: name
    id: name
    attributes:
      label: 嘉宾名称
      description: 姓名、参与的开源之夏项目及角色
    validations:
      required: true
      
  - type: input
    id: github
    attributes:
      label: GitHub
      description:  GitHub 链接，可选

  - type: textarea
    id: expierence
    attributes:
      label: 开源之夏项目经历、角色、参与年份
    validations:
      required: true
    
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com). 
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
