name: 推荐/自荐嘉宾
description: 如果您想推荐或自荐一位嘉宾参与专访，请选择本条模板填写内容
title: '推荐嘉宾 - [姓名/花名/昵称]（专栏）'

body:
  - type: markdown
    attributes:
      value: |
        ### 标题格式
        推荐格式为 `推荐嘉宾 - [推荐人的姓名] （专栏）`；
        例如：`推荐嘉宾 - 张三（任务专访）` `推荐嘉宾 - 李四`
